config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  get 'home/index'

  get 'terms' => 'home#terms'
  get 'about' => 'home#about'

  resource :contacts, only: %i[new create], path_names: {:new => ''} 
  resources :articles do
    resources :comments, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, presence: true, length: { maximum: 140 }
  validates :text, presence: true, length: { maximum: 4000 }

  def subject
    title
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :author, presence: true
  validates :body, presence: true, length: { maximum: 4000 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :info, :warning, :success, :primary, :secondary, :dark

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :find_articles, only: %i[index destroy]
  before_action :find_article, only: %i[show edit update destroy]
  before_action :article_owner, only: %i[edit update destroy]

  def index; end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article
      flash[:success] = t('articles.article_updated')
    else
      render 'edit'
    end
  end

  def new; end

  def show; end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      flash[:success] = t('articles.article_created')
      redirect_to @article
    else
      render 'new'
    end
  end

  def destroy
    if @article.destroy
      render 'index'
    else
      redirect_to @article
    end
  end

  private

  def article_owner
    unless @article.user_id == current_user.id
      flash[:warning] = 'Access denied, as you are not article author'
      redirect_to articles_path
    end
  end

  def article_params
    params.require(:article).permit(:title, :text, :user_id)
  end

  def find_article
    if Article.exists?(params[:id])
      @article = Article.find(params[:id])
    else
      render 'new'
    end
  end

  def find_articles
    @articles = Article.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @article = Article.find(params[:article_id])
    comment = @article.comments.new comment_params
    comment.author = current_user.username
    comment.save
    redirect_to @article
    flash[:success] = t('articles.comment_created')
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new; end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index; end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_flash_messages.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name %>">
		<%= msg %>
	</div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=articles_path%>">Articles</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/articles/edit.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h2 class="display-4"> <%= t('articles.article_edit') %> </h2>
</div>

<div class="container">
<%= form_for @article, method: :put do |f| %>
	<% if @article && @article.errors.any? %>
	<p>	
		<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>	
		</ul>
	</p>
	<% end %>

	<p>
		<%= f.label :tilte %><br/>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br/>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %><hr/>
	</p>

<%end%>
</div>

app/views/articles/index.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1><%= t('articles.article_list') %></h1>
</div>
<div class="container">
  <p>
  	<ol>
  		<% @articles.each do |article| %>
  			<li>
  				<h2><%= article.title %></h2><br/>
  				<p><%= article.text %></p>
  				<p><%= link_to 'Show', article %> |
  					<%= link_to 'Edit', edit_article_url(article) %> |
  					<%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are You sure?' } %>	
  				</p><hr/>
  			</li> 
  		<%end%>	
  	</ol>
  </p>
</div>

app/views/articles/new.html.erb
<h1><%= t('articles.new_article') %></h1>

<%= form_with model: Article.new, local: true do |f| %>
	<% if @article && @article.errors.any? %>
	<p>	
		<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</p>
	<% end %>
	<p>		
		<%= f.label :tilte %><br/>
		<%= f.text_field :title%>
	</p>
	<p>	
		<%= f.label :text %><br/>
		<%= f.text_area :text%>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/show.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h2 class="display-4">Article # <%= @article.id %></h2>
</div>
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<p>
				<%= @article.title %>
			</p>
			<p>
				<%= @article.text %>
			</p><hr/>


			<h3>Comments:</h3>	
			<ul>
				<% @article.comments.each do |comment| %>
					<li>By: <%=comment.author %> | <%= comment.body %><% end %> </li>
				
			</ul>

			<%= link_to 'Show all articles', articles_path %><hr/>

			<h4> <%= t('articles.new_comment') %> </h4>
			<%= form_for ([@article, @article.comments.build]) do |f| %>
				
				<p>
					<%= f.label :body %><br/>
					<%= f.text_area :body %>
				</p>

				<p>
					<%= f.submit %>
				</p><hr/>

			<%end%>
		</div>
	</div>
</div>

app/views/contacts/create.html.erb
<h2><%= t('contacts.thanks') %></h2>

app/views/contacts/new.html.erb
<h2><%= t('contacts.contact_us') %></h2>

<%= form_for :contact, url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %>
	<p>	
		<ul>
		<% @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</p>
	<% end %>

	<p>
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :message %><br/>
		<%= f.text_area :message %>
	</p>

	<p>
		<%= f.submit 'Send message'%>
	</p>

<% end %>

app/views/home/about.html.erb
<h2>About us</h2>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/terms.html.erb
<h2>Here will be terms</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <div class="container">
      <%= render 'flash_messages' %>
    </div>
    
    <% if user_signed_in? %>
      Hello, <%= current_user.username %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>

      

    <%= yield %>
  </body>
</html>